feat: add default user-agent string
Code-Hex/pget pull request #57
Opened 2022-10-18 15:06 UTC by septs

```console
$ pget https://mirrors.tuna.tsinghua.edu.cn/archlinux/iso/latest/archlinux-2022.10.01-x86_64.iso
2.40 KiB / 798.32 MiB [>____________________________________________________________________________________________] 0.00% 1.75 MiB p/s

binding with files...
2.40 KiB / 798.32 MiB [>___________________________________________________________________________________________________] 0.00% ? p/s
$ cat archlinux-2022.10.01-x86_64.iso
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>清华大学 TUNA 镜像站</title>
    <link href="//cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <style> body { padding-top: 40px; } </style>
  </head>
  <body>
    <div class="container">
      <div class="well">
        <p lang="zh-cn">尊敬的访问者，</p>
		<p lang="en">Dear visitor, </p>
		<p lang="fr">Chère cliente, </p>
		<p lang="ja">訪問者へ 、</p>
		<p>&nbsp;</p>
        <p lang="zh-cn">您好！</p>
		<p lang="en">Hello! </p>
		<p lang="fr">Bonjour! </p>
		<p lang="ja">こんにちは ！</p>
		<p>&nbsp;</p>
        <p lang="zh-cn">我们检测到您正在使用移动设备下载镜像站上较大的二进制文件，为防止消耗过多流量，我们建议您改用计算机下载。</p>
		<p lang="en">Your attempt to download a large binary file from a mobile device has been detected. To avoid excessive consumption of data transfer, you are recommended to download it from a computer. </p>
		<p lang="fr">Une tentative de téléchargement d'un fichier binaire de grande taille depuis un appareil mobile a été détectée. Afin d'éviter une consommation excessive de données mobile, nous vous conseillons de recommencer cette action à partir d'un ordinateur. </p>
		<p lang="ja">容量の大きいバイナリファイルが今モバイルデバイスに転送しようとしております、大量のトラフィックが発生するため、コンピュータからのダウンロードをお勧めします。</p>
		<p>&nbsp;</p>
		<p lang="zh-cn">如有疑问，请联系 <a href="mailto:support@tuna.tsinghua.edu.cn">support@tuna.tsinghua.edu.cn</a> 。</p>
		<p lang="en">If there are any possible questions, please contact <a href="mailto:support@tuna.tsinghua.edu.cn">support@tuna.tsinghua.edu.cn</a>. </p>
		<p lang="fr">Pour plus d'informations, veuillez contacter <a href="mailto:support@tuna.tsinghua.edu.cn">support@tuna.tsinghua.edu.cn</a>. </p>
		<p lang="ja">なおご質問などありましたら、<a href="mailto:support@tuna.tsinghua.edu.cn">support@tuna.tsinghua.edu.cn</a>までご連絡してください。</p>
		<p>&nbsp;</p>
                <p><code>00000070 37eec832d885647d98c2056b54651fd4</code></p>
      </div>
    </div>
  </body>
</html>
$ pget --user-agent 'Pget/0.1.1' https://mirrors.tuna.tsinghua.edu.cn/archlinux/iso/latest/archlinux-2022.10.01-x86_64.iso
1.04 MiB / 798.32 MiB [>__________________________________________________________________________________________] 0.13% 894.55 KiB p/s^C
```

2022-10-19 12:23 UTC, Code-Hex commented on download.go
> +			ua = fallback
I don't think necessary the fallback variable.

Can't do like this?

```suggestion
			ua = "Pget/" + version
```

2022-10-19 16:40 UTC, Code-Hex requested changes

2022-10-20 00:14 UTC, septs commented on download.go
> +func WithUserAgent(ua, version string) DownloadOption {
https://github.com/Code-Hex/pget/blob/7c82871216f84e90e83c2abd1a68a497fb6f9246/cmd/pget/main.go#L11

https://github.com/Code-Hex/pget/blob/e73109e6e5ae8ef9fdd9ef71a761dcb0001e5c56/.goreleaser.yml#L7

The `version` variable, only main file

2022-10-20 02:28 UTC, Code-Hex commented on download.go
> +func WithUserAgent(ua, version string) DownloadOption {
I see. I forget my code

2022-10-20 02:28 UTC, Code-Hex approved these changes
Thanks

2022-10-20 02:28 UTC, merged